.PHONY: demo1 demo2 demo3 demo2-fresh demo3-fresh

demo1:
	./prepare-demo1.sh

demo2:
	./prepare-demo2-continued.sh

demo3:
	./prepare-demo3-continued.sh

demo2-fresh:
	./prepare-demo2-fresh.sh

demo3-fresh:
	./prepare-demo3-fresh.sh

rm:
	./destroy-kind.sh 2
