apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-deployment
  namespace: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns
  template:
    metadata:
      labels:
        app: pdns
    spec:
      containers:
      - name: pdns
        args: # From dmc
          - --gmysql-password=$(MARIADB_PASS)
        #  - --api-key=$(POWERDNS_API_KEY)
        image: powerdns/pdns-auth-49:4.9.4
        imagePullPolicy: IfNotPresent
        env:
        - name: PDNS_AUTH_API_KEY
          value: "auth_key"
        - name: MARIADB_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password # Check which key needs to be used for powerdns user
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: api
          containerPort: 8081
          protocol: TCP
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        readinessProbe:
          httpGet:
            path: /
            port: api
        volumeMounts:
        - name: pdns-config-volume
          mountPath: /etc/powerdns/pdns.conf
          subPath: pdns.conf
          readOnly: true
      volumes:
        - name: pdns-config-volume
          configMap:
            name: pdns-config

