---
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: test-authoritative-chaos
spec:
  concurrent: false
  timeouts:
    assert: 150s # Increased from default 60s to allow for chaos injection delays
    cleanup: 60s
  steps:
    - name: Post Test Start
      description: Annotate test start
      try:
        - script:
            content: |
              ../utils/annotate-grafana.sh test-authoritative-start
    - name: Inject Chaos
      description: Inject Chaos and assert destruction
      try:
        - apply:
            resource:
              apiVersion: chaos.datadoghq.com/v1beta1
              kind: Disruption
              metadata:
                name: delete-powerdns-pod
                namespace: dns
              spec:
                selector:
                  app: pdns
                count: 1
                duration: 1m
                containerFailure:
                  forced: false # send a SIGTERM signal to all of the pod's containers
        - assert:
            resource:
              apiVersion: chaos.datadoghq.com/v1beta1
              kind: Disruption
              metadata:
                name: delete-powerdns-pod
                namespace: dns
              status:
                selectedTargetsCount: 1
                ignoredTargetsCount: 0
                injectionStatus: PreviouslyInjected
    - name: Post Test Stop
      description: Annotate test finish
      try:
        - script:
            content: |
              ../utils/annotate-grafana.sh test-authoritative-end
    - name: Validate Revival
      try:
        - assert:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: pdns-deployment
                namespace: dns
              status:
                availableReplicas: 1
                (conditions[?type == 'Available']):
                - status: "True"
    - name: Annotate System Restored
      description: Annotate system restored state
      try:
        - script:
            content: |
              ../utils/annotate-grafana.sh test-authoritative-system-restored